In [157]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [158]:
X = pd.read_csv('Train.csv')
print(X.head());
# Convert X,Y to Numpy arrays
X = X.values
Y=X[:,-1]
X=X[:,:-1]
print(X);
print(Y);

   feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722
[[ 0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [-0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [-1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [-1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]
[ -82.15466656  -48.89796018   77.2703707  ... -107.51050797  -47.34155781
 -115.93900296]


In [159]:
pd.DataFrame(X[:5,:]).head()


0         1         2         3         4
0  0.293416 -0.945599 -0.421105  0.406816  0.525662
1 -0.836084 -0.189228 -0.776403 -1.053831  0.597997
2  0.236425  0.132836 -0.147723  0.699854 -0.187364
3  0.175312  0.143194 -0.581111 -0.122107 -1.292168
4 -1.693011  0.542712 -2.798729 -0.686723  1.244077

In [160]:
ones = np.ones((X.shape[0],1))
X = np.hstack((ones,X))
print(X.shape)


(1600, 6)


In [161]:
def hypothesis(X,theta):
    return np.dot(X,theta)

def error(X,y,theta):
    e = 0.0
    y_ = hypothesis(X,theta)
    e = np.sum((y-y_)**2)
    
    return e/m
    
def gradient(X,y,theta):
    
    y_ = hypothesis(X,theta)
    grad = np.dot(X.T,(y_ - y))
    m = X.shape[0]
    return grad/m

def gradient_descent(X,y,learning_rate = 0.1,max_iters=300):
    
    n = X.shape[1]
    theta = np.zeros((n,))
    error_list = []
    
    for i in range(max_iters):
        e = error(X,y,theta)
        error_list.append(e)
        
        #Gradient descent
        grad = gradient(X,y,theta)
        theta = theta - learning_rate*grad
        
    return theta,error_list

In [162]:
import time
start = time.time()
theta,error_list = gradient_descent(X,Y)
end = time.time()
print("Time taken is ", end-start)

Time taken is  0.02976393699645996


In [163]:
print(theta)


[ 4.99096674 29.68187118 92.66247759  8.28062089 44.76773522  2.51916121]


In [164]:
y_ =[]
x_test=pd.read_csv('./Test/Test.csv')
x_test=x_test.values
ones = np.ones((x_test.shape[0],1))
x_test = np.hstack((ones,x_test))
print(x_test.shape)

m=x_test.shape[0]
for i in range(m):
    pred = hypothesis(x_test[i],theta)
    y_.append(pred)
y_ = np.array(y_)

(400, 6)


In [133]:
print(y_.shape)

(400,)


In [165]:
df = pd.DataFrame(data=y_,columns=["target"])

In [166]:
df.to_csv('y_prediction.csv')
